server:
  port: 9093
eureka:
 client:
   service-url:
     defaultZone: http://eureka-server:8761/eureka/




spring:
    application:
      name: USER-SERVICE
    datasource:
      url: jdbc:mysql://mysql-db:3306/userdb
      password: *****
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect