server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://mongo-db:27017/orderdb
      password: ****
      username: root
      port: 27017
      database: orderdb
      repositories:
        enabled: true

